### PR TITLE
Updated codebase to TexShop 3.81

### PR DESCRIPTION
**Pull request by samkrishna**
Gets the sources caught up to the 3.81 Baseline at Prof. Koch's website.

### CODE REVIEW

**Comment by fingolfin** [comment]
Hi,
Thanks, but that's really not necessary - I have a cron job that downloads all releases, and a script to add them to the repo. Oh, and this PR also omits / skips lots of releases.

I just need to get around to uploading it all. Didn't spend much time on this recently, as I didn't think anybody cared about or was even awareof this repo.

**Comment by fingolfin** [comment]
OK, I added the missing releases (with the possible exception of 3.63 and 3.64, which for some reason I am missing).

If you are interested in this history preserving project, feel free to contact me by mail.

Finally, be warned that I will rewrite the history of this repository at least once more from scratch, to add lots of old versions from the 1.x era, and to correct some release dates and other stuff.

**Comment by samkrishna** [comment]
Ok so what needs to be done to get the PR accepted?

I'm specifically attempting to get the TexShop codebase to build warning-free. That's a little more work than just pushing the repo. I just wanted a baseline PR to work from rather than trying to get all the last 20+ versions caught up. 

Although if that's important to you, then I'll start from 3.6x (or whatever the next version after the last GitHub version is).

**Comment by samkrishna** [comment]
Ok sounds good. 

When do you think you'll have the final rewrite done?

I'd like to get the repo to the point where it's the canonical development repo for the codebase so that more developers could contribute.

**Comment by fingolfin** [comment]
This repository was never created with the purpose of being the "canonical development repository". Of course I'd be happy if TeXShop development were using git; but I tried to get Richard to use Subversion 10 years ago, and that didn't quite work, and I don't think it'd work out now.

And as long as Richard is the primary (and mostly only) developer, the official development will be whatever he releases. Only with his blessing could there ever be a "canonical development repository", to use your wording.

Have you communicated with him about this at all?

**Comment by samkrishna** [comment]
Not yet. I'll ask him about it. 

Thanks!

**Comment by fingolfin** [comment]
FYI, I just reset the history; the new repository contains more than three times as many old TeXShop releases, and is up-to-date till 3.83

**Pull request closed without merging**
